export const THEMES = [
  'light',
  'dark',
  'cupcake',
  'bumblebee',
  'emerald',
  'corporate',
  'synthwave',
  'retro',
  'cyberpunk',
  'valentine',
  'halloween',
  'garden',
  'forest',
  'aqua',
  'lofi',
  'pastel',
  'fantasy',
  'wireframe',
  'black',
  'luxury',
  'dracula',
  'cmyk',
  'autumn',
  'business',
  'acid',
  'lemonade',
  'night',
  'coffee',
  'winter',
  'dim',
  'nord',
  'sunset',
];
export const themeColorMap = {
  dark: '#8AB4F8',
  light: '#3366CC',
  cupcake: '#FF70B3',
  emerald: '#06D6A0',
  synthwave: '#F72585',
  retro: '#F9C74F',
  cyberpunk: '#00F5FF',
  valentine: '#E83E8C',
  halloween: '#FF6D00',
  garden: '#4CAF50',
  forest: '#2E8B57',
  aqua: '#1A9FE0',
  lofi: '#6B7280',
  pastel: '#FFB6C1',
  fantasy: '#C77DFF',
  wireframe: '#94A3B8',
  black: '#7E6BC4',
  luxury: '#D4AF37',
  dracula: '#FF5555',
  cmyk: '#0099CC',
  autumn: '#E76F51',
  business: '#3E7CB1',
  acid: '#AEDC3F',
  lemonade: '#FFDD00',
  night: '#5D5FEF',
  coffee: '#A47551',
  winter: '#48CAE4',
  dim: '#9CA3AF',
  nord: '#81A1C1',
  sunset: '#FD5E53',
};
